import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import React from "react";


const inter = Inter({ subsets: ["latin"] });


const geistSans = localFont({
  src: "../public/fonts/Geist-Sans.woff2",
  variable: "--font-geist-sans",
  display: "swap",
});

const geistMono = localFont({
  src: "../public/fonts/Geist-Mono.woff2",
  variable: "--font-geist-mono",
  display: "swap",
});

export const metadata: Metadata = {
  title: "BudgetWise Financial Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <ClerkProvider>
        <html lang="en">
        <body
            className={`${inter.className} ${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        {children}
        </body>
        </html>
      </ClerkProvider>
  );
}
